import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/nav/header";
import Footer from "@/components/nav/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        /*         className=" min-h-dvh flex flex-col bg-gradient-to-tr from-gray-100 to-sky-200/60"
         */ className=" min-h-dvh flex flex-col "
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
